- name: APP-Deployment
  become: true
  hosts: webserver
  vars_files:
    - vars/main.yml
  roles:
    - setup
    - apache2
    - php
    - composer
    - geerlingguy.mysql
    - deploy
    - security
